-- =============================================================================
-- PROYECTO: LIBRERÍA HIGH-PERFORMANCE (Platinum Spec v5.5)
-- ESTADO: PRODUCTION READY & RLS FIXED
-- =============================================================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- [FIX] WRAPPER INMUTABLE PARA UNACCENT
CREATE OR REPLACE FUNCTION f_unaccent(text)
  RETURNS text AS
$func$
SELECT public.unaccent('public.unaccent', $1)
$func$  LANGUAGE sql IMMUTABLE;

-- 2. ENUMS
CREATE TYPE product_status AS ENUM ('active', 'draft', 'preorder', 'archived');
CREATE TYPE order_status AS ENUM ('pending_whatsapp', 'confirmed', 'cancelled', 'completed');
CREATE TYPE user_role AS ENUM ('admin', 'customer');

-- =============================================================================
-- 3. FUNCIONES DE UTILIDAD (TRIGGERS)
-- =============================================================================

-- Actualizar updated_at
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Crear perfil automáticamente (Sync Auth -> Public)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (NEW.id, NEW.raw_user_meta_data->>'full_name', 'customer');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- 4. TABLAS CORE
-- =============================================================================

CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  role user_role DEFAULT 'customer',
  full_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger: Auth -> Profile
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  isbn TEXT,
  author TEXT NOT NULL,
  
  -- [MEJORA] Soporte Multi-idioma
  language VARCHAR(5) NOT NULL DEFAULT 'es', 
  
  status product_status DEFAULT 'draft',
  price INTEGER NOT NULL CHECK (price >= 0),
  promotional_price INTEGER CHECK (promotional_price >= 0),
  stock_qty INTEGER NOT NULL DEFAULT 0,
  
  cover_image TEXT,
  blurhash TEXT,
  description TEXT,
  specs JSONB DEFAULT '{}'::jsonb,
  
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  
  -- Columna generada para búsqueda rápida (FTS)
  fts_vector tsvector GENERATED ALWAYS AS (
    to_tsvector('spanish', f_unaccent(title || ' ' || author || ' ' || COALESCE(isbn, '')))
  ) STORED
);

CREATE TRIGGER set_products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

CREATE TABLE public.product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  display_order INTEGER DEFAULT 0
);

-- =============================================================================
-- 5. COMBOS (LOGIC + VISTAS)
-- =============================================================================

CREATE TABLE public.bundles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  price INTEGER NOT NULL,
  description TEXT,
  cover_image TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER set_bundles_updated_at
  BEFORE UPDATE ON public.bundles
  FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

CREATE TABLE public.bundle_items (
  bundle_id BIGINT REFERENCES public.bundles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE RESTRICT,
  quantity INTEGER DEFAULT 1,
  PRIMARY KEY (bundle_id, product_id)
);

-- VISTA DE STOCK CALCULADO
CREATE OR REPLACE VIEW public.v_bundles_stock AS
SELECT 
  b.id,
  b.title,
  b.slug,
  b.price,
  b.cover_image,
  b.is_active,
  MIN(FLOOR(p.stock_qty / bi.quantity)::int) as virtual_stock
FROM public.bundles b
JOIN public.bundle_items bi ON b.id = bi.bundle_id
JOIN public.products p ON bi.product_id = p.id
GROUP BY b.id;

-- =============================================================================
-- 6. LEADS & PEDIDOS
-- =============================================================================

CREATE TABLE public.orders_leads (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_contact TEXT NOT NULL,
  shipping_info JSONB,
  cart_snapshot JSONB NOT NULL, 
  total_amount INTEGER NOT NULL,
  is_gift BOOLEAN DEFAULT false,
  status order_status DEFAULT 'pending_whatsapp'
);

CREATE TABLE public.restock_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  customer_contact TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  notified BOOLEAN DEFAULT false
);

-- =============================================================================
-- 7. ÍNDICES AVANZADOS
-- =============================================================================

CREATE INDEX idx_products_slug ON public.products(slug);
CREATE INDEX idx_products_category ON public.products(category_id);
CREATE INDEX idx_products_language ON public.products(language);
CREATE INDEX idx_products_fts ON public.products USING GIN(fts_vector);
CREATE INDEX idx_products_specs ON public.products USING GIN (specs); 
CREATE INDEX idx_orders_status ON public.orders_leads(status);

-- =============================================================================
-- 8. POLÍTICAS RLS (SEGURIDAD DE DATOS)
-- =============================================================================

-- Habilitar RLS en todas las tablas sensibles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bundle_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders_leads ENABLE ROW LEVEL SECURITY;

-- --- PERFILES (PROFILES) - [CORREGIDO v5.5] ---
-- Permitimos que cualquier usuario autenticado pueda leer la tabla de perfiles.
-- Esto es esencial para que la aplicación pueda verificar roles ('admin') sin bloqueos.
CREATE POLICY "Authenticated users can read profiles" 
  ON public.profiles
  FOR SELECT 
  TO authenticated 
  USING (true);

-- Solo los administradores pueden editar roles o datos de perfiles (Seguridad)
CREATE POLICY "Admins can update profiles" 
  ON public.profiles
  FOR UPDATE 
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- --- PRODUCTOS ---
CREATE POLICY "Public Read Active Products" ON public.products
  FOR SELECT USING (status IN ('active', 'preorder') OR auth.role() = 'service_role');

-- La escritura depende de poder leer el rol 'admin' en la tabla profiles
CREATE POLICY "Admin All Access Products" ON public.products
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- --- CATEGORÍAS & IMÁGENES ---
CREATE POLICY "Public Read Categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Admin Manage Categories" ON public.categories FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Public Read Images" ON public.product_images FOR SELECT USING (true);
CREATE POLICY "Admin Manage Images" ON public.product_images FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- --- BUNDLES ---
CREATE POLICY "Public Read Bundles" ON public.bundles
  FOR SELECT USING (is_active = true);

CREATE POLICY "Public Read Bundle Items" ON public.bundle_items FOR SELECT USING (true);

CREATE POLICY "Admin All Access Bundles" ON public.bundles
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );
  
CREATE POLICY "Admin All Access Bundle Items" ON public.bundle_items
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- --- LEADS (PEDIDOS) ---
CREATE POLICY "Public Create Leads" ON public.orders_leads FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin Read Leads" ON public.orders_leads
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- =============================================================================
-- 9. RPC FUNCTIONS
-- =============================================================================

CREATE OR REPLACE FUNCTION check_stock_availability(items jsonb)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  item jsonb;
  current_stock int;
BEGIN
  FOR item IN SELECT * FROM jsonb_array_elements(items)
  LOOP
    SELECT stock_qty INTO current_stock
    FROM public.products
    WHERE id = (item->>'product_id')::bigint;
    
    IF current_stock IS NULL OR current_stock < (item->>'qty')::int THEN
      RETURN false;
    END IF;
  END LOOP;
  RETURN true;
END;
$$;
